plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/lisandroalvo/Desktop/Design  System Live App"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build needed - static site'"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]